(function(){
'use strict';

const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const slug=s=>String(s||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,52);
const STAGES=[
 {id:'caso',label:'Hoja 1 · Informe Directivo',timed:false},
 {id:'preguntas',label:'Hoja 2 · Equipo y consultas',timed:true},
 {id:'despliegue',label:'Hoja 3 · Planificación estratégica',timed:true},
 {id:'reporte',label:'Hoja 4 · Presentación al Directorio',timed:false},
 {id:'evaluacion',label:'Hoja 5 · Resultados',timed:false}
];
const LEGACY_STAGE_IDS={'Lectura del caso':'caso','Consultas a Dirección':'preguntas','Selección de variables':'despliegue','Preparación de la defensa':'despliegue','Presentaciones al Directorio':'reporte','Plenario y cierre':'evaluacion'};
const PANEL_PROMPTS=[
 {title:'Lectura del problema',question:'Claridad de la lectura del problema.'},
 {title:'Hipótesis y decisiones',question:'Coherencia de la hipótesis y las decisiones.'},
 {title:'Sistema',question:'Comprensión de interdependencias y trade-offs.'},
 {title:'Defensa',question:'Calidad de la defensa ante el Directorio.'}
];
const EXAMPLES=[
 {id:'demo_funcional_v59',name:'Mirada funcional',auto:31,panelScore:2.5,total:28,balance:19,status:'Evaluado'},
 {id:'demo_tension_v59',name:'Sistema en tensión',auto:68,panelScore:6.5,total:67,balance:54,status:'Evaluado'},
 {id:'demo_alineada_v59',name:'Sistema alineado',auto:92,panelScore:9.5,total:94,balance:96,status:'Evaluado'}
];
let auth,db,user,sessions=[],activeSession=null,teams=[],unsubSessions=null,unsubTeams=null,rankFilter='real',timerLoop=null,deletingSessionId='',timerEnding=false;
let exposure={running:false,startedAt:0,elapsed:0},exposureLoop=null;
const evaluationWrites=new Map();

function configured(){const c=window.HOSHIN_FIREBASE_CONFIG||{};return !!(c.apiKey&&c.projectId&&!String(c.apiKey).startsWith('REEMPLAZAR'))}
async function sha256(value){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,'0')).join('')}
function stamp(v){if(!v)return 0;if(typeof v.toMillis==='function')return v.toMillis();if(v.seconds)return v.seconds*1000;return Number(v)||0}
function ago(v){const ms=Date.now()-stamp(v);if(!stamp(v))return 'Sin actividad';if(ms<60000)return 'Ahora';if(ms<3600000)return `Hace ${Math.floor(ms/60000)} min`;return `Hace ${Math.floor(ms/3600000)} h`}
function stageById(id){return STAGES.find(stage=>stage.id===id)||STAGES[0]}
function timerStageId(timer={}){return timer.sheetId||LEGACY_STAGE_IDS[timer.stageLabel]||'caso'}
function sessionStatus(raw){return raw==='open'?'open':raw==='paused'?'paused':raw==='finished'?'finished':'closed'}
function statusLabel(raw){const s=sessionStatus(raw);return s==='open'?'Abierta':s==='paused'?'Pausada':s==='finished'?'Finalizada':'Cerrada'}
function loginMessage(text){$('loginMessage').textContent=text||'';$('loginMessage').classList.toggle('show',!!text)}
function panelNumber(value){const n=Number(String(value??'').replace(',','.'));return Number.isFinite(n)?Math.round(n*10)/10:0}
function panelLabel(value){const n=panelNumber(value);return Number.isInteger(n)?String(n):n.toFixed(1).replace('.',',')}
function evaluation(raw={}){const direct=panelNumber(raw.score??raw.panelScore),legacy=[raw.means,raw.interdep,raw.catchball,raw.defense].map(Number),legacyScore=legacy.some(v=>Number.isFinite(v)&&v>0)?legacy.reduce((sum,v)=>sum+(Number.isFinite(v)?v:0),0)/2:0,score=Math.max(0,Math.min(10,direct||legacyScore)),completed=raw.completed===true||(raw.completed===undefined&&score>=1);return {score:panelNumber(score),completed}}
function blankDiagnosis(){return {ratings:{},agreements:{growth:'',inventory:'',capabilities:'',coordination:''},hypothesis:''}}
function blankTeam(id,name){return {id,name,roles:{},positions:{},questions:[],unlocked:[],internal:{},eric:{zones:{unclassified:[],eliminate:[],reduce:[],increase:[],create:[]},problem:'',movement:''},diagnosis:blankDiagnosis(),customVars:[],selected:[],alloc:{},manager:{problem:'',hypothesis:'',portfolio:'',conditions:'',speech:''},facilitator:false,stageClosures:{},round1:null,reportStatus:'pending',feedback:[],rethink:{learning:'',keep:'',change:'',extra:0,interdep:'',agreement:''},final:null,a3:[],eval:{score:0,completed:false}}}
function activeDeviceCount(t){const devices=t.activeDevices||{};return Object.values(devices).filter(value=>Date.now()-stamp(value)<180000).length}
function writeEvaluation(id,e){const sessionId=activeSession.id,key=`${sessionId}/${id}`,previous=evaluationWrites.get(key)||Promise.resolve(),next=previous.catch(()=>{}).then(()=>db.doc(`workshops/${sessionId}/teams/${id}`).update({evaluation:e,updatedAt:firebase.firestore.FieldValue.serverTimestamp()}));evaluationWrites.set(key,next);next.finally(()=>{if(evaluationWrites.get(key)===next)evaluationWrites.delete(key)});return next}
function result(t){const m=t.metrics||{},e=evaluation(t.evaluation),panelScore=e.score,defenseScore=Math.round(panelScore*10),ready=!!t.progress?.presentationReady,evaluated=e.completed&&panelScore>=1&&panelScore<=10,excluded=!!t.rankingExcluded;return {id:t.id,name:t.name,auto:Number(m.auto||0),avg:Number(m.avg||0),balance:Number(m.balance||0),sp:Number(m.sp||0),inter:Number(m.inter||0),panelScore,defenseScore,total:ready&&evaluated&&!excluded?Math.round(Number(m.auto||0)*.5+defenseScore*.5):null,ready,evaluated,excluded,status:excluded?'Excluido del ranking':!ready?'Presentación pendiente':!evaluated?'Evaluación pendiente':'Evaluado',t}}
function rank(rows){const ranked=rows.filter(r=>r.total!==null).sort((a,b)=>b.total-a.total||b.panelScore-a.panelScore||b.auto-a.auto||a.name.localeCompare(b.name,'es'));let last='',position=0;ranked.forEach((r,i)=>{const key=`${r.total}|${r.panelScore}|${r.auto}`;r.position=key===last?position:i+1;last=key;position=r.position});return [...ranked,...rows.filter(r=>r.total===null).sort((a,b)=>a.name.localeCompare(b.name,'es'))]}

function init(){
 if(!configured()||!window.firebase){loginMessage('Firebase todavía no está configurado. Completá firebase-config.js y seguí SETUP-FIREBASE.md.');return}
 firebase.initializeApp(window.HOSHIN_FIREBASE_CONFIG);auth=firebase.auth();db=firebase.firestore();db.enablePersistence({synchronizeTabs:true}).catch(()=>{});bind();
 auth.onAuthStateChanged(async u=>{if(!u){showLogin();return}const role=await db.doc(`users/${u.uid}`).get().catch(()=>null);if(!role?.exists||role.data().role!=='facilitator'){await auth.signOut();loginMessage('La cuenta no tiene rol de facilitador.');return}user=u;showApp();subscribeSessions()});
}
function bind(){
 $('loginForm').onsubmit=async e=>{e.preventDefault();try{await auth.signInWithEmailAndPassword($('loginEmail').value.trim(),$('loginPassword').value)}catch(_){loginMessage('No fue posible ingresar. Revisá las credenciales.')}};
 $('logoutBtn').onclick=()=>auth.signOut();$('sessionForm').onsubmit=createSession;$('teamForm').onsubmit=createTeam;$('publishRankingBtn').onclick=publishRanking;$('hideRankingBtn').onclick=hideRanking;$('deleteSessionBtn').onclick=deleteSession;$('exportBtn').onclick=exportData;$('closeDetail').onclick=()=>$('detailModal').style.display='none';
 $('sessionPrimaryBtn').onclick=sessionPrimaryAction;$('finishSessionBtn').onclick=finishSession;$('stagePrimaryBtn').onclick=stagePrimaryAction;$('timerAdd').onclick=()=>addTime(300);
 $('reopenBtn').onclick=()=>setReopen(true);$('closeReopenBtn').onclick=()=>setReopen(false);$('reopenTimeBtn').onclick=assignReopenTime;$('drawOrderBtn').onclick=drawPresentationOrder;
 $('exposureToggle').onclick=toggleExposure;$('exposureReset').onclick=resetExposure;
 document.querySelectorAll('[data-preview]').forEach(button=>button.onclick=()=>openPreview(button.dataset.preview));
 document.querySelectorAll('[data-rank-filter]').forEach(button=>button.onclick=()=>{rankFilter=button.dataset.rankFilter;document.querySelectorAll('[data-rank-filter]').forEach(x=>x.classList.toggle('active',x===button));renderRanking()});
 $('timerStage').disabled=true;
}
function showLogin(){$('loginView').classList.remove('hidden');$('facilitatorApp').classList.add('hidden');unsubSessions?.();unsubTeams?.();user=null}
function showApp(){$('loginView').classList.add('hidden');$('facilitatorApp').classList.remove('hidden');$('userLabel').textContent=user.email;$('connectionState').textContent='Conectado'}
function subscribeSessions(){unsubSessions?.();unsubSessions=db.collection('workshops').where('facilitatorUid','==',user.uid).onSnapshot(s=>{sessions=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>stamp(b.createdAt)-stamp(a.createdAt));renderSessions();if(activeSession){const fresh=sessions.find(x=>x.id===activeSession.id);if(fresh){activeSession=fresh;renderWorkspace()}else selectSession(null)}})}
function renderSessions(){$('sessionList').innerHTML=sessions.length?sessions.map(s=>`<button class="session-item ${activeSession?.id===s.id?'active':''}" onclick="Facilitator.selectSession('${esc(s.id)}')"><b>${esc(s.name)}</b><span>${esc(s.id.toUpperCase())} · ${statusLabel(s.status)}</span></button>`).join(''):'<div class="empty">Todavía no hay experiencias.</div>'}
async function createSession(e){e.preventDefault();const id=slug($('sessionCode').value),name=$('sessionName').value.trim();if(!id||!name)return;const ref=db.doc(`workshops/${id}`);if((await ref.get()).exists)return alert('Ese código ya existe.');const now=Date.now();await ref.set({name,code:id.toUpperCase(),status:'closed',facilitatorUid:user.uid,rankingPublished:false,presentationOrder:[],timer:{status:'ready',sheetId:'caso',stageIndex:0,stageLabel:STAGES[0].label,durationSec:0,remainingSec:0,endAt:null,cycleId:`caso-${now}`},createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});$('sessionForm').reset();setTimeout(()=>selectSession(id),300)}
function selectSession(id){unsubTeams?.();activeSession=sessions.find(s=>s.id===id)||null;teams=[];renderSessions();renderWorkspace();if(!activeSession)return;unsubTeams=db.collection(`workshops/${id}/teams`).onSnapshot(s=>{teams=s.docs.map(d=>({id:d.id,...d.data()}));renderTeams();renderWorkspace()})}

function sessionPrimaryConfig(){const status=sessionStatus(activeSession?.status);if(status==='open')return {label:'Pausar experiencia',next:'paused'};if(status==='paused')return {label:'Reanudar experiencia',next:'open'};if(status==='finished')return {label:'Reabrir experiencia',next:'open'};return {label:'Abrir experiencia',next:'open'}}
async function sessionPrimaryAction(){if(!activeSession)return;const cfg=sessionPrimaryConfig();if(sessionStatus(activeSession.status)==='finished'&&!confirm('¿Reabrir la experiencia finalizada? Los datos se conservarán.'))return;await db.doc(`workshops/${activeSession.id}`).update({status:cfg.next,updatedAt:firebase.firestore.FieldValue.serverTimestamp()})}
async function finishSession(){if(!activeSession||!confirm('¿Finalizar la experiencia? Los datos quedarán en modo de consulta y no se permitirán nuevas modificaciones salvo reapertura del facilitador.'))return;await db.doc(`workshops/${activeSession.id}`).update({status:'finished',updatedAt:firebase.firestore.FieldValue.serverTimestamp()})}

function timerRemaining(timer=activeSession?.timer||{}){if(timer.status==='running'&&timer.endAt)return Math.max(0,Math.ceil((stamp(timer.endAt)-Date.now())/1000));return Number(timer.remainingSec||timer.durationSec||0)}
function currentTimer(){const raw=activeSession?.timer||{},sheetId=timerStageId(raw),stage=stageById(sheetId);return {...raw,sheetId,stageIndex:Math.max(0,STAGES.findIndex(x=>x.id===sheetId)),stageLabel:stage.label,status:raw.status==='idle'?'ready':raw.status||'ready'}}
function stageStateLabel(index,timer=currentTimer()){
 const current=timer.stageIndex;
 if(index>current)return 'No habilitada';
 const reopened=teams.some(t=>reopenIsActive(t.stageOverrides?.[STAGES[index].id]));if(reopened)return 'Reabierta excepcionalmente';
 if(index<current)return 'Cerrada';
 if(timer.status==='ready')return 'Habilitada, sin iniciar';
 if(timer.status==='running'||timer.status==='paused')return 'En curso';
 if(timer.status==='ended')return STAGES[index].timed?'Tiempo finalizado':'Cerrada';
 return 'No habilitada';
}
function renderWorkspace(){
 const on=!!activeSession;$('sessionWorkspace').classList.toggle('hidden',!on);$('rankingCard').classList.toggle('hidden',!on);$('noSession').classList.toggle('hidden',on);if(!on)return;
 const status=sessionStatus(activeSession.status),sessionCfg=sessionPrimaryConfig(),timer=currentTimer(),stage=stageById(timer.sheetId);
 $('activeSessionName').textContent=activeSession.name;$('activeSessionCode').textContent=activeSession.id.toUpperCase();$('activeSessionStatus').textContent=statusLabel(status);$('activeSessionStatus').className=`tag ${status}`;$('rankingStatus').textContent=activeSession.rankingPublished?'Resultados publicados':'Resultados ocultos';
 $('sessionPrimaryBtn').textContent=sessionCfg.label;$('finishSessionBtn').disabled=status==='finished';$('finishSessionBtn').classList.toggle('hidden',status==='finished'||status==='closed');
 $('participantActiveStage').textContent=`Etapa activa para los participantes: ${stage.label}`;let activeStateText=stageStateLabel(timer.stageIndex,timer);if(timer.sheetId==='despliegue'&&timer.status==='ended'){const pendingReports=teams.filter(team=>!team.progress?.presentationReady);activeStateText=pendingReports.length?`Tiempo finalizado. Esperando la generación de: ${pendingReports.map(team=>team.name).join(', ')}.`:'Tiempo finalizado. Todas las presentaciones fueron preparadas y guardadas correctamente.'}$('participantActiveState').textContent=activeStateText;
 $('kpiTeams').textContent=teams.length;$('kpiOnline').textContent=teams.filter(t=>Date.now()-stamp(t.lastSeen)<150000).length;$('kpiReady').textContent=teams.filter(t=>t.progress?.presentationReady).length;$('kpiProgress').textContent=(teams.length?Math.round(teams.reduce((a,t)=>a+Number(t.progress?.percent||0),0)/teams.length):0)+'%';$('kpiRanking').textContent=activeSession.rankingPublished?'Publicados':'Ocultos';
 renderTimer();renderStageStates();renderReopenTeams();renderPresentationOrder();renderRanking();
}
function renderStageStates(){const timer=currentTimer();$('stageStates').innerHTML=STAGES.map((stage,index)=>`<div class="stage-state ${index===timer.stageIndex?'current':''}"><b>${esc(stage.label)}</b><span>${esc(stageStateLabel(index,timer))}</span></div>`).join('')}
function renderTimer(){
 clearInterval(timerLoop);
 const tick=()=>{
  if(!activeSession)return;const t=currentTimer(),stage=stageById(t.sheetId),seconds=timerRemaining(t),timed=stage.timed,expired=t.status==='ended'||timed&&t.status==='running'&&seconds===0,mm=String(Math.floor(seconds/60)).padStart(2,'0'),ss=String(seconds%60).padStart(2,'0');
  $('timerStage').value=stage.id;$('timerStageDisplay').textContent=stage.label;$('timerStatusDisplay').textContent=stageStateLabel(t.stageIndex,t);$('timerClock').textContent=timed&&t.status!=='ready'?`${mm}:${ss}`:'--:--';$('timerMinutes').disabled=!timed||t.status!=='ready';$('timerAdd').disabled=!timed||t.status!=='running'||expired;
  const btn=$('stagePrimaryBtn');if(t.status==='ready')btn.textContent=timed?'Iniciar etapa':'Habilitar etapa';else if(t.status==='running'||t.status==='paused')btn.textContent='Finalizar etapa ahora';else if(t.stageIndex<STAGES.length-1)btn.textContent='Habilitar hoja siguiente';else btn.textContent='Reabrir etapa';
  $('stageActionHelp').textContent=t.status==='ready'?(timed?'Los participantes podrán editar cuando inicies el cronómetro.':'La etapa quedará disponible sin cronómetro.'):(t.status==='running'||t.status==='paused')?'Finalizar guarda y bloquea; no avanza de hoja.':t.stageIndex<STAGES.length-1?'La siguiente hoja se habilita solo cuando lo decidas.':'La última etapa está cerrada.';
  if(timed&&t.status==='running'&&seconds===0&&!timerEnding){timerEnding=true;endStage().finally(()=>{timerEnding=false})}
 };
 tick();timerLoop=setInterval(tick,1000);
}
async function writeTimer(timer){if(activeSession)await db.doc(`workshops/${activeSession.id}`).update({timer,updatedAt:firebase.firestore.FieldValue.serverTimestamp()})}
async function stagePrimaryAction(){const t=currentTimer(),stage=stageById(t.sheetId);if(t.status==='ready')return startStage(stage);if(t.status==='running'||t.status==='paused')return endStage();if(t.status==='ended'&&t.stageIndex<STAGES.length-1)return enableNextStage();if(t.status==='ended')return setReopen(true,stage.id,'all')}
async function startStage(stage){const now=Date.now(),durationSec=stage.timed?Math.max(60,Number($('timerMinutes').value||20)*60):0;await writeTimer({sheetId:stage.id,stageIndex:STAGES.findIndex(x=>x.id===stage.id),stageLabel:stage.label,durationSec,remainingSec:durationSec,status:'running',cycleId:`${stage.id}-${now}`,startedAt:firebase.firestore.FieldValue.serverTimestamp(),endAt:stage.timed?firebase.firestore.Timestamp.fromMillis(now+durationSec*1000):null})}
async function endStage(){const t=currentTimer();await writeTimer({...t,status:'ended',remainingSec:0,endAt:null,endedAt:firebase.firestore.FieldValue.serverTimestamp()})}
async function enableNextStage(){
 const t=currentTimer();
 if(t.sheetId==='despliegue'){const reopened=teams.filter(team=>reopenIsActive(team.stageOverrides?.despliegue));if(reopened.length)return alert(`Todavía no se puede habilitar la Hoja 4. Cerrá primero la reapertura de: ${reopened.map(x=>x.name).join(', ')}.`);const pending=teams.filter(team=>!team.progress?.presentationReady);if(pending.length)return alert(`Todavía no se puede habilitar la Hoja 4. Falta guardar o generar la presentación de: ${pending.map(x=>x.name).join(', ')}. Pediles que mantengan la pantalla abierta; si hubo un error, pueden reintentar desde la Hoja 3.`)}
 const next=STAGES[Math.min(STAGES.length-1,t.stageIndex+1)],now=Date.now(),durationSec=next.timed?Math.max(60,Number($('timerMinutes').value||20)*60):0,status=next.timed?'ready':'running';
 await writeTimer({sheetId:next.id,stageIndex:STAGES.findIndex(x=>x.id===next.id),stageLabel:next.label,durationSec,remainingSec:durationSec,status,cycleId:`${next.id}-${now}`,startedAt:status==='running'?firebase.firestore.FieldValue.serverTimestamp():null,endAt:null});
}
async function addTime(sec){const t=currentTimer(),stage=stageById(t.sheetId);if(!stage.timed||t.status!=='running')return;const remainingSec=timerRemaining(t)+sec;await writeTimer({...t,remainingSec,endAt:firebase.firestore.Timestamp.fromMillis(Date.now()+remainingSec*1000)})}

function reopenIsActive(value){if(!value)return false;if(value===true)return true;if(value.open===false)return false;const until=stamp(value.expiresAt);return !until||until>Date.now()}
function targetTeams(selection){return selection==='all'?teams:teams.filter(t=>t.id===selection)}
async function setReopen(open,forcedStage,forcedTeam){
 if(!activeSession)return;const stageId=forcedStage||$('reopenStage').value,selection=forcedTeam||$('reopenTeam').value,targets=targetTeams(selection);if(!targets.length)return alert('No hay equipos para aplicar la acción.');
 const stageIndex=STAGES.findIndex(stage=>stage.id===stageId),timer=currentTimer();if(open&&stageIndex>timer.stageIndex)return alert('No se puede reabrir una hoja futura. Primero debe habilitarse siguiendo el avance normal de la experiencia.');if(open&&stageIndex===timer.stageIndex&&timer.status!=='ended')return alert('Esa etapa ya está habilitada. La reapertura solo se utiliza sobre una etapa cerrada o con tiempo finalizado.');
 if(open&&!confirm('Reabrir esta etapa permitirá modificar información ya cerrada. Esta acción no recalculará ni eliminará datos automáticamente. ¿Continuar?'))return;
 const actionId=`${stageId}-${Date.now()}-${randomChars(4).toLowerCase()}`,batch=db.batch();targets.forEach(team=>{const changes={[`stageOverrides.${stageId}`]:open?{open:true,openedAt:Date.now(),expiresAt:null}:{open:false,closedAt:Date.now(),closeCycle:actionId},updatedAt:firebase.firestore.FieldValue.serverTimestamp()};if(stageId==='despliegue'){changes['progress.presentationReady']=false;changes['progress.reportStatus']=open?'reopened':'regenerating'}batch.update(db.doc(`workshops/${activeSession.id}/teams/${team.id}`),changes)});await batch.commit();
}
async function assignReopenTime(){if(!activeSession)return;const stageId=$('reopenStage').value,targets=targetTeams($('reopenTeam').value),minutes=Math.max(1,Math.min(60,Number($('reopenMinutes').value||5))),expiresAt=Date.now()+minutes*60000,timer=currentTimer(),stageIndex=STAGES.findIndex(stage=>stage.id===stageId);if(!targets.length)return alert('No hay equipos para aplicar el tiempo adicional.');if(stageIndex>timer.stageIndex)return alert('No se puede asignar tiempo a una hoja futura.');if(stageIndex===timer.stageIndex&&timer.status!=='ended')return alert('El tiempo adicional se asigna solamente a una etapa cerrada o con tiempo finalizado.');const batch=db.batch();targets.forEach(team=>{const changes={[`stageOverrides.${stageId}`]:{open:true,openedAt:Date.now(),expiresAt},updatedAt:firebase.firestore.FieldValue.serverTimestamp()};if(stageId==='despliegue'){changes['progress.presentationReady']=false;changes['progress.reportStatus']='reopened'}batch.update(db.doc(`workshops/${activeSession.id}/teams/${team.id}`),changes)});await batch.commit();alert(`Se asignaron ${minutes} minutos adicionales. Este tiempo corresponde solo a la reapertura y no reinicia el cronómetro general.`)}
function renderReopenTeams(){const current=$('reopenTeam').value;$('reopenTeam').innerHTML='<option value="all">Todos los equipos</option>'+teams.slice().sort((a,b)=>a.name.localeCompare(b.name,'es')).map(t=>`<option value="${esc(t.id)}">${esc(t.name)}</option>`).join('');if([...$('reopenTeam').options].some(o=>o.value===current))$('reopenTeam').value=current}

function randomChars(length){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',bytes=new Uint8Array(length);crypto.getRandomValues(bytes);return Array.from(bytes,b=>chars[b%chars.length]).join('')}
function randomPin(){const bytes=new Uint32Array(1);crypto.getRandomValues(bytes);return String(100000+(bytes[0]%900000))}
async function uniqueTeamId(name){const base=slug(name).slice(0,24)||'equipo';for(let i=0;i<12;i++){const id=`${base}-${randomChars(4).toLowerCase()}`;if(!(await db.doc(`workshops/${activeSession.id}/teams/${id}`).get()).exists)return id}throw new Error('No se pudo generar un código único. Intentá nuevamente.')}
async function createTeam(e){e.preventDefault();if(!activeSession)return;const name=$('newTeamName').value.trim();if(!name)return;const submit=e.submitter;submit.disabled=true;try{const id=await uniqueTeamId(name),pin=randomPin(),proof=await sha256(`${activeSession.id}|${id}|${pin}`),batch=db.batch(),ref=db.doc(`workshops/${activeSession.id}/teams/${id}`);batch.set(ref,{name,code:id.toUpperCase(),state:blankTeam(id,name),progress:{percent:0,currentSection:'caso',currentLabel:'Sin ingresar',rolesAssigned:0,questions:0,variables:0,fundedVariables:0,presentationReady:false,reportStatus:'pending'},metrics:{avg:0,balance:0,sp:0,auto:0,inter:0},evaluation:evaluation(),rankingExcluded:false,locked:false,stageOverrides:{},activeDevices:{},stateRevision:0,createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp(),lastSeen:null});batch.set(db.doc(`workshops/${activeSession.id}/teamSecrets/${id}`),{proof,pin,createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});await batch.commit();const url=inviteUrl(id);$('teamCreationResult').innerHTML=`<div class="invite"><b>Acceso creado para ${esc(name)}</b><br>Equipo: <b>${esc(name)}</b><br>Enlace de acceso: ${esc(url)}<br>PIN: <b>${esc(pin)}</b></div>`;$('teamForm').reset()}catch(error){alert(error.message||'No se pudo crear el equipo.')}finally{submit.disabled=false}}
function renderTeams(){$('teamsGrid').innerHTML=teams.length?teams.slice().sort((a,b)=>a.name.localeCompare(b.name,'es')).map(teamCard).join(''):'<div class="empty">Creá el primer equipo.</div>'}
function teamCard(t){const p=t.progress||{},m=t.metrics||{},e=evaluation(t.evaluation),r=result(t),online=Date.now()-stamp(t.lastSeen)<150000,devices=activeDeviceCount(t),prompts=PANEL_PROMPTS.map(x=>`<article class="dialogue-prompt"><b>${esc(x.title)}</b><p>${esc(x.question)}</p></article>`).join(''),reopened=Object.keys(t.stageOverrides||{}).filter(id=>reopenIsActive(t.stageOverrides[id])).map(id=>stageById(id).label);
 return `<article class="team-card"><div class="team-card-head"><div><h3>${esc(t.name)}</h3><div class="team-code">${esc(t.id.toUpperCase())}</div></div><span class="presence">${online?'Activo':ago(t.lastSeen)}${devices>1?` · ${devices} sesiones`:''}</span></div><div class="progress-row"><div class="progress"><i style="width:${Number(p.percent||0)}%"></i></div><b>${Number(p.percent||0)}%</b></div><div class="team-metrics"><div class="mini"><span>Consultas</span><b>${Number(p.questions||0)}/3</b></div><div class="mini"><span>Variables</span><b>${Number(p.variables||0)}/7</b></div><div class="mini"><span>SP</span><b>${Number(m.sp||0)}/18</b></div><div class="mini"><span>Score auto</span><b>${Number(m.auto||0)}</b></div></div><div class="team-status"><b>${esc(p.currentLabel||'Sin ingresar')}</b> · ${esc(r.status)}${reopened.length?` · Reabierta: ${esc(reopened.join(', '))}`:''}</div><div class="team-actions"><button class="btn tiny" onclick="Facilitator.showDetail('${esc(t.id)}')">Ver detalle</button><button class="btn tiny" onclick="Facilitator.copyInvite('${esc(t.id)}')">Copiar acceso</button><button class="btn tiny" onclick="Facilitator.renameTeam('${esc(t.id)}')">Renombrar</button><button class="btn tiny" onclick="Facilitator.regeneratePin('${esc(t.id)}')">Nuevo PIN</button><button class="btn tiny ${t.locked?'':'red'}" onclick="Facilitator.toggleLock('${esc(t.id)}',${!t.locked})">${t.locked?'Reanudar equipo':'Pausar equipo'}</button><button class="btn tiny" onclick="Facilitator.toggleRanking('${esc(t.id)}',${!t.rankingExcluded})">${t.rankingExcluded?'Incluir en ranking':'No participa del ranking'}</button><button class="btn tiny red" onclick="Facilitator.deleteTeam('${esc(t.id)}')">Eliminar</button></div><details class="evaluation"><summary>Evaluación del Directorio · ${e.completed?panelLabel(e.score)+'/10':'pendiente'}</summary><div class="dialogue-head"><b>Guía para la conversación</b><span>Conversen los cuatro componentes; no se califican por separado.</span></div><div class="dialogue-grid">${prompts}</div><div class="score-entry"><label>Nota consensuada del Directorio <span>Obligatoria · 1 a 10</span><input type="number" min="1" max="10" step="0.1" value="${e.score||''}" placeholder="Ej.: 7" ${e.completed?'disabled':''} onchange="Facilitator.setEvaluation('${esc(t.id)}',this.value)"></label><span class="eval-confirm">${e.completed?`Evaluación registrada correctamente: ${panelLabel(e.score)}/10.`:'Ingresá una única nota para finalizar.'}</span><button class="btn tiny ${e.completed?'':'primary'}" onclick="Facilitator.finalizeEvaluation('${esc(t.id)}',${!e.completed})">${e.completed?'Editar evaluación':'Finalizar evaluación'}</button></div></details></article>`}
async function setEvaluation(id,value){const t=teams.find(x=>x.id===id);if(!t)return;const score=panelNumber(value);if(score<1||score>10){alert('La nota debe ser un número entre 1 y 10.');return renderTeams()}const e={score,completed:false};t.evaluation=e;await writeEvaluation(id,e)}
async function finalizeEvaluation(id,complete){const t=teams.find(x=>x.id===id),e=evaluation(t?.evaluation);if(!t)return;if(complete&&(e.score<1||e.score>10))return alert('Ingresá una única nota numérica del 1 al 10 antes de finalizar.');e.completed=!!complete;t.evaluation=e;await writeEvaluation(id,e)}

function renderRanking(){
 if(!activeSession)return;const real=rank(teams.map(result)),examples=rank(EXAMPLES.map(x=>({...x,id:x.id,ready:true,evaluated:true,excluded:false}))),rows=rankFilter==='examples'?examples:rankFilter==='all'?rank([...real,...examples]):real,winner=(rankFilter==='examples'?examples:real).find(r=>r.total!==null);
 const active=real.filter(r=>!r.excluded),pending=active.filter(r=>!r.ready||!r.evaluated);$('rankingReadiness').innerHTML=pending.length?`<div class="invite"><b>Publicación todavía bloqueada.</b><br>Falta completar: ${pending.map(r=>`${esc(r.name)} (${esc(r.status)})`).join(', ')}.</div>`:`<div class="invite"><b>Listo para publicar.</b> Todos los equipos que participan del ranking tienen presentación y evaluación.</div>`;
 $('winnerBanner').innerHTML=winner?`<div class="winner-banner"><div class="medal">1.º</div><div><h3>${esc(winner.name)}</h3><p>${rankFilter==='examples'?'Ejemplo de referencia':'Equipo ganador calculado'} · nota ${panelLabel(winner.panelScore)}/10 · score automático ${winner.auto}/100</p></div><strong>${winner.total}</strong></div>`:'<div class="empty">El ganador aparecerá cuando todos los equipos activos tengan presentación y evaluación.</div>';
 $('rankingRows').innerHTML=rows.map(r=>`<tr class="${r.position&&r.position<=3?'p'+r.position:''}"><td><span class="rank">${r.position?r.position+'.º':'—'}</span></td><td><b>${esc(r.name)}</b></td><td>${r.auto}</td><td>${r.evaluated?panelLabel(r.panelScore)+'/10':'—'}</td><td><span class="total">${r.total??'—'}</span></td><td>${r.balance}/100</td><td><span class="state-pill ${r.total===null?'pending':'ready'}">${esc(r.status)}</span></td><td>${r.t?`<button class="btn tiny" onclick="Facilitator.showDetail('${esc(r.id)}')">Ver</button>`:'Referencia'}</td></tr>`).join('')||'<tr><td colspan="8">Sin datos.</td></tr>';
}
async function publishRanking(){if(!activeSession)return;const all=teams.map(result),pending=all.filter(r=>!r.excluded&&(!r.ready||!r.evaluated));if(pending.length)return alert(`Todavía no se puede publicar. Falta completar: ${pending.map(r=>r.name+' — '+r.status).join(', ')}. Podés evaluar cada equipo o marcarlo como “No participa del ranking”.`);const rows=rank(all.filter(r=>!r.excluded)).filter(r=>r.total!==null).map(r=>({position:r.position,teamId:r.id,name:r.name,auto:r.auto,panelScore:r.panelScore,total:r.total}));if(!rows.length)return alert('No hay equipos evaluados para publicar.');if(!confirm(`Se publicarán los resultados de ${rows.length} equipo${rows.length===1?'':'s'} en todas las pantallas. ¿Continuar?`))return;const batch=db.batch();batch.set(db.doc(`workshops/${activeSession.id}/public/ranking`),{published:true,rows,publishedAt:firebase.firestore.FieldValue.serverTimestamp(),publishedBy:user.uid});batch.update(db.doc(`workshops/${activeSession.id}`),{rankingPublished:true,updatedAt:firebase.firestore.FieldValue.serverTimestamp()});await batch.commit();alert('Resultados publicados y actualizados en todas las pantallas.')}
async function hideRanking(){if(!activeSession)return;const batch=db.batch();batch.set(db.doc(`workshops/${activeSession.id}/public/ranking`),{published:false,rows:[]},{merge:true});batch.update(db.doc(`workshops/${activeSession.id}`),{rankingPublished:false,updatedAt:firebase.firestore.FieldValue.serverTimestamp()});await batch.commit()}
async function toggleRanking(id,value){await db.doc(`workshops/${activeSession.id}/teams/${id}`).update({rankingExcluded:!!value,updatedAt:firebase.firestore.FieldValue.serverTimestamp()})}

async function drawPresentationOrder(){if(!activeSession||!teams.length)return alert('Primero creá los equipos.');if(teams.some(t=>evaluation(t.evaluation).completed))return alert('El sorteo ya no puede repetirse porque comenzó la evaluación de las presentaciones.');const shuffled=teams.map(t=>t.id);for(let i=shuffled.length-1;i>0;i--){const bytes=new Uint32Array(1);crypto.getRandomValues(bytes);const j=bytes[0]%(i+1);[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]]}const names=shuffled.map(id=>teams.find(t=>t.id===id)?.name||id);if(!confirm(`Orden sorteado:\n\n${names.map((name,i)=>`${i+1}. ${name}`).join('\n')}\n\n¿Confirmar y guardar este orden?`))return;await db.doc(`workshops/${activeSession.id}`).update({presentationOrder:shuffled,presentationOrderAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()})}
function renderPresentationOrder(){const order=Array.isArray(activeSession?.presentationOrder)?activeSession.presentationOrder:[];$('presentationOrder').innerHTML=order.length?order.map((id,index)=>`<span class="order-item"><b>${index+1}.</b> ${esc(teams.find(t=>t.id===id)?.name||id)}</span>`).join(''):'<span class="sub">Todavía no se confirmó un orden.</span>';$('drawOrderBtn').disabled=teams.some(t=>evaluation(t.evaluation).completed)}

function guidePrompts(t){const selected=new Set(t.state?.selected||[]),prompts=['Hoja 1: ¿Qué dato del Informe Directivo cambió la primera interpretación del equipo?','Hoja 1: ¿Qué tensión entre crecimiento, eficiencia y capacidad conviene hacer visible antes de avanzar?'];if(selected.has('promociones'))prompts.push('Promociones: ¿el volumen incremental compensa margen y presión operativa?');if(selected.has('digital_tools')||selected.has('automatizacion'))prompts.push('E-commerce y digital: ¿qué proceso, dato y hábito deben estabilizarse antes de automatizar?');if(selected.has('horas_extra'))prompts.push('Horas extra: ¿se está reduciendo desperdicio o simplemente quitando cobertura?');if(selected.has('centralizadas')||selected.has('estandares_tienda'))prompts.push('Autonomía: ¿qué decisiones deben tener reglas comunes y cuáles conviene mantener locales?');if(selected.has('cap_comercial')||selected.has('feedback_managers'))prompts.push('Capacitación: ¿qué práctica observable y qué rutina de liderazgo convertirán formación en desempeño?');if(selected.has('frecuencia')||selected.has('cross_selling'))prompts.push('Información y CRM: ¿qué evidencia falta para justificar la intervención y medir incrementalidad?');return prompts}
function showDetail(id){const t=teams.find(x=>x.id===id);if(!t)return;const s=t.state||{},m=s.manager||{},diagnosis=s.diagnosis||{},selected=s.selected||[],alloc=s.alloc||{},a3=Array.isArray(s.a3)?s.a3:[];$('detailTitle').textContent=t.name;$('detailContent').innerHTML=`<div class="detail-grid"><div class="detail"><b>Hipótesis preliminar</b><p>${esc(diagnosis.hypothesis||m.problem||s.eric?.problem||'Pendiente')}</p></div><div class="detail"><b>Hipótesis de resolución</b><p>${esc(m.hypothesis||'Pendiente')}</p></div><div class="detail"><b>Lógica del portafolio</b><p>${esc(m.portfolio||m.logic||'Pendiente')}</p></div><div class="detail"><b>Condiciones críticas</b><p>${esc(m.conditions||'Pendiente')}</p></div><div class="detail"><b>Variables seleccionadas</b><p>${selected.length?selected.map(x=>`${esc(x)} (${Number(alloc[x]||0)} SP)`).join('<br>'):'Pendiente'}</p></div><div class="detail"><b>A3 prioritarios</b><p>${a3.length?a3.map((x,i)=>`${i+1}. ${esc(x.title||'Sin título')} · Prioridad ${esc(x.priority||i+1)}`).join('<br>'):'Pendiente'}</p></div></div><div class="private-guide"><h3>Guía privada del facilitador</h3><ul>${guidePrompts(t).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`;$('detailModal').style.display='grid'}

async function renameTeam(id){const t=teams.find(x=>x.id===id);if(!t)return;const name=prompt('Nuevo nombre del equipo:',t.name);if(!name?.trim()||name.trim()===t.name)return;await db.doc(`workshops/${activeSession.id}/teams/${id}`).update({name:name.trim(),'state.name':name.trim(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()})}
async function regeneratePin(id){const t=teams.find(x=>x.id===id);if(!t||!confirm(`¿Generar un nuevo PIN para ${t.name}? El PIN anterior dejará de servir para nuevos ingresos.`))return;const pin=randomPin(),proof=await sha256(`${activeSession.id}|${id}|${pin}`);await db.doc(`workshops/${activeSession.id}/teamSecrets/${id}`).set({proof,pin,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});alert(`Nuevo PIN de ${t.name}: ${pin}\n\nUsá “Copiar acceso” para compartir el mensaje completo.`)}
async function copyInvite(id){const t=teams.find(x=>x.id===id);if(!t)return;const secret=await db.doc(`workshops/${activeSession.id}/teamSecrets/${id}`).get(),pin=secret.data()?.pin;if(!pin)return alert('Este equipo fue creado con una versión anterior y no tiene el PIN recuperable. Usá “Nuevo PIN” y luego “Copiar acceso”.');const message=`Equipo: ${t.name}\nEnlace de acceso: ${inviteUrl(id)}\nPIN: ${pin}`;await navigator.clipboard.writeText(message);alert('Acceso completo copiado: equipo, enlace y PIN.')}
async function toggleLock(id,value){await db.doc(`workshops/${activeSession.id}/teams/${id}`).update({locked:!!value,updatedAt:firebase.firestore.FieldValue.serverTimestamp()})}
async function deleteTeam(id){const t=teams.find(x=>x.id===id);if(!t||!confirm(`¿Eliminar el equipo “${t.name}”? Esta acción eliminará sus datos y accesos.`))return;const members=await db.collection(`workshops/${activeSession.id}/members`).where('teamId','==',id).get(),batch=db.batch();members.docs.forEach(doc=>batch.delete(doc.ref));batch.delete(db.doc(`workshops/${activeSession.id}/teams/${id}`));batch.delete(db.doc(`workshops/${activeSession.id}/teamSecrets/${id}`));await batch.commit()}
function inviteUrl(id){const u=new URL('index.html',location.href);u.searchParams.set('session',activeSession.id.toUpperCase());u.searchParams.set('team',id.toUpperCase());return u.href}

async function deleteDocumentRefs(refs){for(let i=0;i<refs.length;i+=400){const batch=db.batch();refs.slice(i,i+400).forEach(ref=>batch.delete(ref));await batch.commit()}}
async function deleteSession(){if(!activeSession||deletingSessionId)return;const session={...activeSession},teamCount=teams.length,base=`workshops/${session.id}`;let closedForDeletion=false;if(session.facilitatorUid!==user.uid)return alert('Solo podés eliminar experiencias creadas por tu cuenta.');if(!confirm(`¿Eliminar definitivamente “${session.name}”?\n\nSe eliminarán ${teamCount} equipo${teamCount===1?'':'s'}, sus accesos y los resultados publicados. No hace falta escribir el código, pero esta versión no tiene papelera y la acción es irreversible.`))return;const button=$('deleteSessionBtn');deletingSessionId=session.id;button.disabled=true;button.textContent='Eliminando…';try{await db.doc(base).update({status:'closed',updatedAt:firebase.firestore.FieldValue.serverTimestamp()});closedForDeletion=true;const collections=['teams','teamSecrets','members','public'],snapshots=await Promise.all(collections.map(name=>db.collection(`${base}/${name}`).get({source:'server'}))),childRefs=snapshots.flatMap(snapshot=>snapshot.docs.map(doc=>doc.ref));await deleteDocumentRefs([...childRefs,db.doc(base)]);unsubTeams?.();unsubTeams=null;sessions=sessions.filter(x=>x.id!==session.id);activeSession=null;teams=[];renderSessions();renderWorkspace();alert(`La experiencia “${session.name}” fue eliminada.`)}catch(error){console.error(error);alert(closedForDeletion?'No se completó la eliminación. La experiencia quedó cerrada y puede intentarse nuevamente.':'No se pudo iniciar la eliminación; no se modificó la experiencia.')}finally{deletingSessionId='';button.disabled=false;button.textContent='Eliminar experiencia'}}

function openPreview(stage){const u=new URL('index.html',location.href);u.searchParams.set('demo','1');u.searchParams.set('sheet',stage);u.searchParams.set('facilitatorPreview','1');window.open(u.href,'_blank','noopener')}
function toggleExposure(){if(exposure.running){exposure.elapsed+=Date.now()-exposure.startedAt;exposure.running=false}else{exposure.startedAt=Date.now();exposure.running=true}renderExposure()}
function resetExposure(){exposure={running:false,startedAt:0,elapsed:0};renderExposure()}
function renderExposure(){clearInterval(exposureLoop);const tick=()=>{const ms=exposure.elapsed+(exposure.running?Date.now()-exposure.startedAt:0),sec=Math.floor(ms/1000),mm=String(Math.floor(sec/60)).padStart(2,'0'),ss=String(sec%60).padStart(2,'0');$('exposureClock').textContent=`${mm}:${ss}`;$('exposureToggle').textContent=exposure.running?'Pausar':'Iniciar'};tick();exposureLoop=setInterval(tick,1000)}
function exportData(){if(!activeSession)return;const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),version:'v59',workshop:activeSession,teams,formula:'50% score automático + 50% nota consensuada del Directorio (1 a 10)'},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`hoshin-${activeSession.id}.json`;a.click();URL.revokeObjectURL(a.href)}

window.Facilitator={selectSession,showDetail,setEvaluation,finalizeEvaluation,toggleLock,toggleRanking,deleteTeam,copyInvite,renameTeam,regeneratePin};
init();renderExposure();
})();
