(function(){
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const slug=s=>String(s||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,64);
const STAGES=['Lectura del caso','Consultas a Dirección','Selección de variables','Preparación de la defensa','Presentaciones al Directorio','Plenario y cierre'];
const PANEL_PROMPTS=[
 {title:'Fines–medios',question:'¿La propuesta conecta con claridad el diagnóstico, los objetivos y las variables elegidas?'},
 {title:'Interdependencias',question:'¿El equipo reconoce las coordinaciones, secuencias y condiciones necesarias entre áreas?'},
 {title:'Catchball',question:'¿Escucha, revisa supuestos y construye compromisos a partir del intercambio?'},
 {title:'Defensa',question:'¿Explica decisiones y trade-offs con claridad y responde de manera consistente?'}
];
const EXAMPLES=[
 {id:'demo_funcional_v55',name:'Mirada funcional',type:'Ejemplo',auto:31,panelScore:2.5,defenseScore:25,total:28,balance:19,status:'Evaluado',comment:'Agendas funcionales, contradicciones y baja integración.'},
 {id:'demo_tension_v55',name:'Sistema en tensión',type:'Ejemplo',auto:68,panelScore:6.5,defenseScore:65,total:67,balance:54,status:'Evaluado',comment:'Hipótesis sistémica con tensiones todavía abiertas.'},
 {id:'demo_alineada_v55',name:'Sistema alineado',type:'Ejemplo',auto:92,panelScore:9.5,defenseScore:95,total:94,balance:96,status:'Evaluado',comment:'Cadena causal clara, recursos coherentes y condiciones explícitas.'}
];
let auth,db,user,sessions=[],activeSession=null,teams=[],unsubSessions=null,unsubTeams=null,rankFilter='real',timerLoop=null,deletingSessionId='';
const evaluationWrites=new Map();
function configured(){const c=window.HOSHIN_FIREBASE_CONFIG||{};return !!(c.apiKey&&c.projectId&&!String(c.apiKey).startsWith('REEMPLAZAR'))}
async function sha256(value){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,'0')).join('')}
function stamp(v){if(!v)return 0;if(typeof v.toMillis==='function')return v.toMillis();if(v.seconds)return v.seconds*1000;return Number(v)||0}
function ago(v){const ms=Date.now()-stamp(v);if(!stamp(v))return 'Sin actividad';if(ms<60000)return 'Ahora';if(ms<3600000)return `Hace ${Math.floor(ms/60000)} min`;return `Hace ${Math.floor(ms/3600000)} h`}
function loginMessage(text){$('loginMessage').textContent=text||'';$('loginMessage').classList.toggle('show',!!text)}
function panelNumber(value){const n=Number(String(value??'').replace(',','.'));return Number.isFinite(n)?Math.round(n*10)/10:0}
function panelLabel(value){const n=panelNumber(value);return Number.isInteger(n)?String(n):n.toFixed(1).replace('.',',')}
function evaluation(raw={}){const direct=panelNumber(raw.score??raw.panelScore),legacy=[raw.means,raw.interdep,raw.catchball,raw.defense].map(Number),legacyScore=legacy.some(v=>Number.isFinite(v)&&v>0)?legacy.reduce((sum,v)=>sum+(Number.isFinite(v)?v:0),0)/2:0,score=Math.max(0,Math.min(10,direct||legacyScore)),completed=raw.completed===true||(raw.completed===undefined&&score>=1);return {score:panelNumber(score),comment:String(raw.comment||''),completed}}
function writeEvaluation(id,e){const sessionId=activeSession.id,key=`${sessionId}/${id}`,previous=evaluationWrites.get(key)||Promise.resolve(),next=previous.catch(()=>{}).then(()=>db.doc(`workshops/${sessionId}/teams/${id}`).update({evaluation:e,updatedAt:firebase.firestore.FieldValue.serverTimestamp()}));evaluationWrites.set(key,next);next.then(()=>{if(evaluationWrites.get(key)===next)evaluationWrites.delete(key)},()=>{if(evaluationWrites.get(key)===next)evaluationWrites.delete(key)});return next}
function result(t){const m=t.metrics||{},e=evaluation(t.evaluation),panelScore=e.score,defenseScore=Math.round(panelScore*10),ready=!!t.progress?.presentationReady,evaluated=e.completed&&panelScore>=1&&panelScore<=10;return {id:t.id,name:t.name,type:'Equipo real',auto:Number(m.auto||0),avg:Number(m.avg||0),balance:Number(m.balance||0),sp:Number(m.sp||0),inter:Number(m.inter||0),evaluation:e,panelScore,defenseScore,total:ready&&evaluated?Math.round(Number(m.auto||0)*.5+defenseScore*.5):null,ready,evaluated,status:!ready?'Presentación pendiente':!evaluated?'Pendiente de evaluación':'Evaluado',t}}
function rank(rows){const ranked=rows.filter(r=>r.total!==null).sort((a,b)=>b.total-a.total||b.panelScore-a.panelScore||b.auto-a.auto||a.name.localeCompare(b.name,'es'));let last='',position=0;ranked.forEach((r,i)=>{const key=`${r.total}|${r.panelScore}|${r.auto}`;r.position=key===last?position:i+1;last=key;position=r.position});return [...ranked,...rows.filter(r=>r.total===null).sort((a,b)=>a.name.localeCompare(b.name,'es'))]}
function blankTeam(id,name){return {id,name,roles:{},positions:{},questions:[],unlocked:[],internal:{},eric:{zones:{unclassified:[],eliminate:[],reduce:[],increase:[],create:[]},problem:'',movement:''},customVars:[],selected:[],alloc:{},manager:{problem:'',hypothesis:'',portfolio:'',conditions:'',speech:''},facilitator:false,round1:null,feedback:[],rethink:{learning:'',keep:'',change:'',extra:0,interdep:'',agreement:''},final:null,a3:{},eval:{score:0,comment:'',completed:false}}}
function init(){
 if(!configured()||!window.firebase){loginMessage('Firebase todavía no está configurado. Completá firebase-config.js y seguí SETUP-FIREBASE.md.');return}
 firebase.initializeApp(window.HOSHIN_FIREBASE_CONFIG);auth=firebase.auth();db=firebase.firestore();db.enablePersistence({synchronizeTabs:true}).catch(()=>{});bind();
 auth.onAuthStateChanged(async u=>{if(!u){showLogin();return}const role=await db.doc(`users/${u.uid}`).get().catch(()=>null);if(!role?.exists||role.data().role!=='facilitator'){await auth.signOut();loginMessage('La cuenta no tiene rol de facilitador.');return}user=u;showApp();subscribeSessions()});
}
function bind(){
 $('loginForm').onsubmit=async e=>{e.preventDefault();try{await auth.signInWithEmailAndPassword($('loginEmail').value.trim(),$('loginPassword').value)}catch(_){loginMessage('No fue posible ingresar. Revisá las credenciales.')}};
 $('logoutBtn').onclick=()=>auth.signOut();$('sessionForm').onsubmit=createSession;$('teamForm').onsubmit=createTeam;$('publishRankingBtn').onclick=publishRanking;$('publishRankingBtn2').onclick=publishRanking;$('hideRankingBtn').onclick=hideRanking;$('deleteSessionBtn').onclick=deleteSession;$('exportBtn').onclick=exportData;$('closeDetail').onclick=()=>$('detailModal').style.display='none';
 document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>setSessionStatus(b.dataset.status));document.querySelectorAll('[data-rank-filter]').forEach(b=>b.onclick=()=>{rankFilter=b.dataset.rankFilter;document.querySelectorAll('[data-rank-filter]').forEach(x=>x.classList.toggle('active',x===b));renderRanking()});
 $('timerStart').onclick=startTimer;$('timerPause').onclick=pauseTimer;$('timerResume').onclick=resumeTimer;$('timerAdd').onclick=()=>addTime(300);$('timerReset').onclick=resetTimer;$('timerNext').onclick=nextStage;$('timerEnd').onclick=endTimer;
}
function showLogin(){$('loginView').classList.remove('hidden');$('facilitatorApp').classList.add('hidden');unsubSessions?.();unsubTeams?.();user=null}
function showApp(){$('loginView').classList.add('hidden');$('facilitatorApp').classList.remove('hidden');$('userLabel').textContent=user.email;$('connectionState').textContent='Conectado'}
function subscribeSessions(){unsubSessions?.();unsubSessions=db.collection('workshops').where('facilitatorUid','==',user.uid).onSnapshot(s=>{sessions=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>stamp(b.createdAt)-stamp(a.createdAt));renderSessions();if(activeSession){const fresh=sessions.find(x=>x.id===activeSession.id);if(fresh){activeSession=fresh;renderWorkspace()}else selectSession(null)}})}
function renderSessions(){$('sessionList').innerHTML=sessions.length?sessions.map(s=>`<button class="session-item ${activeSession?.id===s.id?'active':''}" onclick="Facilitator.selectSession('${esc(s.id)}')"><b>${esc(s.name)}</b><span>${esc(s.id.toUpperCase())} · ${statusLabel(s.status)}</span></button>`).join(''):'<div class="empty">Todavía no hay experiencias.</div>'}
function statusLabel(s){return s==='open'?'Abierta':s==='paused'?'Pausada':s==='closed'?'Cerrada':'Borrador'}
async function createSession(e){e.preventDefault();const id=slug($('sessionCode').value),name=$('sessionName').value.trim();if(!id||!name)return;const ref=db.doc(`workshops/${id}`);if((await ref.get()).exists)return alert('Ese código ya existe.');await ref.set({name,code:id.toUpperCase(),status:'draft',facilitatorUid:user.uid,rankingPublished:false,timer:{status:'idle',stageLabel:'',durationSec:0,remainingSec:0,endAt:null},createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});$('sessionForm').reset();setTimeout(()=>selectSession(id),300)}
function selectSession(id){unsubTeams?.();activeSession=sessions.find(s=>s.id===id)||null;teams=[];renderSessions();renderWorkspace();if(!activeSession)return;unsubTeams=db.collection(`workshops/${id}/teams`).onSnapshot(s=>{teams=s.docs.map(d=>({id:d.id,...d.data()}));renderTeams();renderWorkspace()})}
function renderWorkspace(){const on=!!activeSession;$('sessionWorkspace').classList.toggle('hidden',!on);$('rankingCard').classList.toggle('hidden',!on);$('noSession').classList.toggle('hidden',on);if(!on)return;$('activeSessionName').textContent=activeSession.name;$('activeSessionCode').textContent=activeSession.id.toUpperCase();$('activeSessionStatus').textContent=statusLabel(activeSession.status);$('activeSessionStatus').className=`tag ${activeSession.status||''}`;$('rankingStatus').textContent=activeSession.rankingPublished?'Podio publicado':'Podio oculto';$('kpiTeams').textContent=teams.length;$('kpiOnline').textContent=teams.filter(t=>Date.now()-stamp(t.lastSeen)<150000).length;$('kpiReady').textContent=teams.filter(t=>t.progress?.presentationReady).length;$('kpiProgress').textContent=(teams.length?Math.round(teams.reduce((a,t)=>a+Number(t.progress?.percent||0),0)/teams.length):0)+'%';$('kpiRanking').textContent=activeSession.rankingPublished?'Publicado':'Oculto';renderTimer();renderRanking()}
async function setSessionStatus(status){if(activeSession)await db.doc(`workshops/${activeSession.id}`).update({status,updatedAt:firebase.firestore.FieldValue.serverTimestamp()})}
async function deleteDocumentRefs(refs){for(let i=0;i<refs.length;i+=400){const batch=db.batch();refs.slice(i,i+400).forEach(ref=>batch.delete(ref));await batch.commit()}}
async function deleteSession(){if(!activeSession||deletingSessionId)return;const session={...activeSession},code=session.id.toUpperCase(),teamCount=teams.length,base=`workshops/${session.id}`;let closedForDeletion=false;if(session.facilitatorUid!==user.uid)return alert('Solo podés eliminar experiencias creadas por tu cuenta.');if(!confirm(`¿Eliminar definitivamente “${session.name}” (${code})?\n\nTambién se eliminarán sus ${teamCount} equipo${teamCount===1?'':'s'}, accesos y ranking. Esta acción no se puede deshacer.`))return;const button=$('deleteSessionBtn');deletingSessionId=session.id;if(button){button.disabled=true;button.textContent='Eliminando…'}try{await db.doc(base).update({status:'closed',updatedAt:firebase.firestore.FieldValue.serverTimestamp()});closedForDeletion=true;const collections=['teams','teamSecrets','members','public'],snapshots=await Promise.all(collections.map(name=>db.collection(`${base}/${name}`).get({source:'server'}))),childRefs=snapshots.flatMap(snapshot=>snapshot.docs.map(doc=>doc.ref));await deleteDocumentRefs([...childRefs,db.doc(base)]);unsubTeams?.();unsubTeams=null;sessions=sessions.filter(x=>x.id!==session.id);activeSession=null;teams=[];renderSessions();renderWorkspace();alert(`La experiencia “${session.name}” fue eliminada por completo.`)}catch(error){console.error('No se pudo eliminar la experiencia',error);alert(closedForDeletion?'No se pudo completar la eliminación. La experiencia continúa visible y quedó cerrada por seguridad; podés intentarlo nuevamente.':'No se pudo iniciar la eliminación. La experiencia no fue modificada.')}finally{deletingSessionId='';const currentButton=$('deleteSessionBtn');if(currentButton){currentButton.disabled=false;currentButton.textContent='Eliminar experiencia'}}}
async function createTeam(e){e.preventDefault();if(!activeSession)return;const name=$('newTeamName').value.trim(),id=slug($('newTeamCode').value),pin=$('newTeamPin').value.trim();if(!name||!id||pin.length<4)return alert('Completá nombre, código y PIN.');const ref=db.doc(`workshops/${activeSession.id}/teams/${id}`);if((await ref.get()).exists)return alert('Ese código ya existe.');const proof=await sha256(`${activeSession.id}|${id}|${pin}`),batch=db.batch();batch.set(ref,{name,code:id.toUpperCase(),state:blankTeam(id,name),progress:{percent:0,currentSection:'caso',currentLabel:'Sin ingresar',rolesAssigned:0,questions:0,variables:0,fundedVariables:0,presentationReady:false},metrics:{avg:0,balance:0,sp:0,auto:0,inter:0},evaluation:evaluation(),locked:false,createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp(),lastSeen:null});batch.set(db.doc(`workshops/${activeSession.id}/teamSecrets/${id}`),{proof,createdAt:firebase.firestore.FieldValue.serverTimestamp()});await batch.commit();const url=inviteUrl(id);$('teamCreationResult').innerHTML=`<div class="invite"><b>Acceso creado para ${esc(name)}</b><br>Experiencia: <b>${activeSession.id.toUpperCase()}</b> · Equipo: <b>${id.toUpperCase()}</b> · PIN: <b>${esc(pin)}</b><br>${esc(url)}</div>`;$('teamForm').reset()}
function renderTeams(){$('teamsGrid').innerHTML=teams.length?teams.slice().sort((a,b)=>a.name.localeCompare(b.name,'es')).map(teamCard).join(''):'<div class="empty">Creá el primer equipo.</div>'}
function teamCard(t){const p=t.progress||{},m=t.metrics||{},e=evaluation(t.evaluation),r=result(t),online=Date.now()-stamp(t.lastSeen)<150000,prompts=PANEL_PROMPTS.map(x=>`<article class="dialogue-prompt"><b>${esc(x.title)}</b><p>${esc(x.question)}</p></article>`).join('');return `<article class="team-card"><div class="team-card-head"><div><h3>${esc(t.name)}</h3><div class="team-code">${esc(t.id.toUpperCase())}</div></div><span class="presence">${online?'Activo':ago(t.lastSeen)}</span></div><div class="progress-row"><div class="progress"><i style="width:${Number(p.percent||0)}%"></i></div><b>${Number(p.percent||0)}%</b></div><div class="team-metrics"><div class="mini"><span>Consultas</span><b>${Number(p.questions||0)}/3</b></div><div class="mini"><span>Variables</span><b>${Number(p.variables||0)}/7</b></div><div class="mini"><span>SP</span><b>${Number(m.sp||0)}/18</b></div><div class="mini"><span>Score auto</span><b>${Number(m.auto||0)}</b></div></div><div class="team-status"><b>${esc(p.currentLabel||'Sin ingresar')}</b> · ${r.status}</div><div class="team-actions"><button class="btn tiny" onclick="Facilitator.showDetail('${esc(t.id)}')">Ver detalle</button><button class="btn tiny" onclick="Facilitator.copyInvite('${esc(t.id)}')">Copiar acceso</button><button class="btn tiny ${t.locked?'':'red'}" onclick="Facilitator.toggleLock('${esc(t.id)}',${!t.locked})">${t.locked?'Reabrir':'Pausar'}</button><button class="btn tiny red" onclick="Facilitator.deleteTeam('${esc(t.id)}')">Eliminar</button></div><details class="evaluation"><summary>Evaluación del Panel · ${e.completed?panelLabel(e.score)+'/10':'pendiente'}</summary><div class="dialogue-head"><b>Guía para el diálogo del Panel</b><span>Conversen los cuatro criterios; no se califican por separado.</span></div><div class="dialogue-grid">${prompts}</div><div class="panel-score-row"><label>Nota final del Panel <span>Obligatoria · de 1 a 10</span><input type="number" min="1" max="10" step="0.1" value="${e.score||''}" placeholder="Ej.: 8,5" onchange="Facilitator.setEvaluation('${esc(t.id)}','score',this.value)"></label><label>Síntesis del diálogo <span>Opcional</span><textarea placeholder="Anotá la conclusión principal del Panel" onchange="Facilitator.setEvaluation('${esc(t.id)}','comment',this.value)">${esc(e.comment)}</textarea></label></div><div class="eval-comment"><span>${e.completed?'Evaluación finalizada. Reabrila si necesitás cambiar la nota.':'Ingresá una nota para poder finalizar.'}</span><button class="btn tiny ${e.completed?'':'primary'}" onclick="Facilitator.finalizeEvaluation('${esc(t.id)}',${!e.completed})">${e.completed?'Reabrir':'Finalizar evaluación'}</button></div></details></article>`}
async function setEvaluation(id,key,value){const t=teams.find(x=>x.id===id),e=evaluation(t?.evaluation);if(!t)return;if(key==='comment')e.comment=String(value);else{const score=panelNumber(value);e.score=score?Math.max(1,Math.min(10,score)):0}e.completed=false;t.evaluation=e;await writeEvaluation(id,e)}
async function finalizeEvaluation(id,value){const t=teams.find(x=>x.id===id),e=evaluation(t?.evaluation);if(!t)return;if(value&&(e.score<1||e.score>10))return alert('Ingresá una única nota numérica del 1 al 10 antes de finalizar.');e.completed=!!value;t.evaluation=e;await writeEvaluation(id,e)}
function renderRanking(){if(!activeSession)return;const real=rank(teams.map(result)),examples=rank(EXAMPLES.map(x=>({...x,ready:true,evaluated:true,evaluation:{score:x.panelScore,comment:x.comment,completed:true}})));const rows=rankFilter==='examples'?examples:rankFilter==='all'?rank([...real,...examples]):real;const winner=(rankFilter==='examples'?examples:real).find(r=>r.total!==null);$('winnerBanner').innerHTML=winner?`<div class="winner-banner"><div class="medal">1.º</div><div><h3>${esc(winner.name)}</h3><p>${rankFilter==='examples'?'Ejemplo de referencia':'Equipo ganador de la experiencia'} · nota del Panel ${panelLabel(winner.panelScore)}/10 · score automático ${winner.auto}/100</p></div><strong>${winner.total}</strong></div>`:'<div class="empty">El ganador aparecerá cuando exista al menos un equipo real con presentación y evaluación finalizadas.</div>';$('rankingRows').innerHTML=rows.map(r=>`<tr class="${r.position&&r.position<=3?'p'+r.position:''}"><td><span class="rank">${r.position?r.position+'.º':'—'}</span></td><td><b>${esc(r.name)}</b></td><td>${r.type}</td><td>${r.auto}</td><td>${r.total===null?'—':panelLabel(r.panelScore)+'/10'}</td><td><span class="total">${r.total??'—'}</span></td><td>${r.balance}/100</td><td><span class="state-pill ${r.total===null?'pending':'ready'}">${r.status}</span></td><td>${r.type==='Equipo real'?`<button class="btn tiny" onclick="Facilitator.showDetail('${esc(r.id)}')">Ver</button>`:'Referencia'}</td></tr>`).join('')||'<tr><td colspan="9">Sin datos.</td></tr>'}
function timerRemaining(timer=activeSession?.timer||{}){if(timer.status==='running'&&timer.endAt)return Math.max(0,Math.ceil((stamp(timer.endAt)-Date.now())/1000));return Number(timer.remainingSec||timer.durationSec||0)}
function renderTimer(){clearInterval(timerLoop);const tick=()=>{const t=activeSession?.timer||{},s=timerRemaining(t),mm=String(Math.floor(s/60)).padStart(2,'0'),ss=String(s%60).padStart(2,'0');$('timerStageDisplay').textContent=t.stageLabel||'Sin etapa activa';$('timerStatusDisplay').textContent=t.status==='running'?'En curso':t.status==='paused'?'Pausado':t.status==='ended'||t.status==='running'&&s===0?'Tiempo cumplido':'Esperando inicio';$('timerClock').textContent=t.status==='idle'||!t.status?'--:--':`${mm}:${ss}`};tick();timerLoop=setInterval(tick,1000)}
async function writeTimer(timer){if(activeSession)await db.doc(`workshops/${activeSession.id}`).update({timer,updatedAt:firebase.firestore.FieldValue.serverTimestamp()})}
async function startTimer(){const durationSec=Math.max(60,Number($('timerMinutes').value||20)*60),stageLabel=$('timerStage').value;await writeTimer({stageLabel,durationSec,remainingSec:durationSec,status:'running',startedAt:firebase.firestore.FieldValue.serverTimestamp(),endAt:firebase.firestore.Timestamp.fromMillis(Date.now()+durationSec*1000)})}
async function pauseTimer(){const t=activeSession?.timer||{},remainingSec=timerRemaining(t);await writeTimer({...t,status:'paused',remainingSec,endAt:null})}
async function resumeTimer(){const t=activeSession?.timer||{},remainingSec=Math.max(0,timerRemaining(t));await writeTimer({...t,status:'running',remainingSec,endAt:firebase.firestore.Timestamp.fromMillis(Date.now()+remainingSec*1000)})}
async function addTime(sec){const t=activeSession?.timer||{},remainingSec=timerRemaining(t)+sec,endAt=t.status==='running'?firebase.firestore.Timestamp.fromMillis(Date.now()+remainingSec*1000):null;await writeTimer({...t,remainingSec,endAt})}
async function resetTimer(){const t=activeSession?.timer||{},durationSec=Number(t.durationSec||Number($('timerMinutes').value||20)*60);await writeTimer({...t,status:'paused',remainingSec:durationSec,endAt:null})}
async function endTimer(){const t=activeSession?.timer||{};await writeTimer({...t,status:'ended',remainingSec:0,endAt:null})}
async function nextStage(){const current=activeSession?.timer?.stageLabel||$('timerStage').value,index=Math.max(0,STAGES.indexOf(current)),next=STAGES[Math.min(STAGES.length-1,index+1)];$('timerStage').value=next;await startTimer()}
function showDetail(id){const t=teams.find(x=>x.id===id);if(!t)return;const s=t.state||{},m=s.manager||{},selected=s.selected||[],alloc=s.alloc||{};$('detailTitle').textContent=t.name;$('detailContent').innerHTML=`<div class="detail-grid"><div class="detail"><b>Lectura del problema</b><p>${esc(m.problem||s.eric?.problem||'Pendiente')}</p></div><div class="detail"><b>Hipótesis de resolución</b><p>${esc(m.hypothesis||'Pendiente')}</p></div><div class="detail"><b>Lógica del portafolio</b><p>${esc(m.portfolio||m.logic||'Pendiente')}</p></div><div class="detail"><b>Condiciones críticas</b><p>${esc(m.conditions||'Pendiente')}</p></div><div class="detail"><b>Variables seleccionadas</b><p>${selected.length?selected.map(x=>`${esc(x)} (${Number(alloc[x]||0)} SP)`).join('<br>'):'Pendiente'}</p></div></div>`;$('detailModal').style.display='grid'}
async function publishRanking(){if(!activeSession)return;const rows=rank(teams.map(result)).filter(r=>r.total!==null).map(r=>({position:r.position,teamId:r.id,name:r.name,avg:r.avg,balance:r.balance,sp:r.sp,auto:r.auto,panelScore:r.panelScore,defenseScore:r.defenseScore,total:r.total,evaluation:r.evaluation}));if(!rows.length)return alert('No hay equipos reales con presentación y evaluación finalizadas.');const batch=db.batch();batch.set(db.doc(`workshops/${activeSession.id}/public/ranking`),{published:true,rows,publishedAt:firebase.firestore.FieldValue.serverTimestamp(),publishedBy:user.uid});batch.update(db.doc(`workshops/${activeSession.id}`),{rankingPublished:true});await batch.commit();alert('Podio real publicado.')}
async function hideRanking(){if(!activeSession)return;const batch=db.batch();batch.set(db.doc(`workshops/${activeSession.id}/public/ranking`),{published:false,rows:[]},{merge:true});batch.update(db.doc(`workshops/${activeSession.id}`),{rankingPublished:false});await batch.commit()}
async function toggleLock(id,value){await db.doc(`workshops/${activeSession.id}/teams/${id}`).update({locked:!!value})}
async function deleteTeam(id){if(!confirm('¿Eliminar este equipo?'))return;const batch=db.batch();batch.delete(db.doc(`workshops/${activeSession.id}/teams/${id}`));batch.delete(db.doc(`workshops/${activeSession.id}/teamSecrets/${id}`));await batch.commit()}
function inviteUrl(id){const u=new URL('index.html',location.href);u.searchParams.set('session',activeSession.id.toUpperCase());u.searchParams.set('team',id.toUpperCase());return u.href}
function copyInvite(id){navigator.clipboard.writeText(inviteUrl(id));alert('Enlace copiado. Compartí el PIN por separado.')}
function exportData(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),workshop:activeSession,teams,formula:'50% score automático + 50% nota final del Panel (1 a 10)'},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`hoshin-${activeSession?.id||'export'}.json`;a.click()}
window.Facilitator={selectSession,showDetail,setEvaluation,finalizeEvaluation,toggleLock,deleteTeam,copyInvite};init();
})();
